openapi: 3.0.9
info:
  title: Sample API
  version: 0.0.1
  description: 'This is a sample API developed with API-First method.'
  termsOfService: http://anandpath.in/terms/
  contact:
    name: Anand Pathak
    email: anandpath@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about AnandPath
  url: http://anandpath.in
servers:
  - url: http://localhost:8080/sample
    description: Local Dev environment
tags:
  - name: sample
    description: This is my Sample API project
    externalDocs:
      description: Find out more about AnandPath
      url: http://anandpath.in
paths:
  /v1/greetings/{name}:
    get:
      tags: [ Sample ]
      summary: Greeting API
      description: Pass in your name and get personalized Greeting
      operationId: greet
      parameters:
        - in: header
          name: channel
          required: false
          example: yz
          schema:
            type: string
            maxLength: 100
        - $ref: '#/components/parameters/name'
#      requestBody:
#        description: Created user object
#        content:
#          'application/json':
#            schema:
#              $ref: '#/components/schemas/User'
#        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: string
#        400:
#          description: Bad request
#          content:
#            application/json:
#              schema:
#                $ref: 'SomeRespnoseStructure'


components:
  parameters:
    name:
      name: name
      in: path
      description: The input name var
      required: true
      schema:
        type: string
        maxLength: 10
  schemas:
    SomeResponse:
      type: object
      properties:
        someField:
          type: string
          description: some description
          example: xxx