spring:
  application:
    name: 'sample'
server:
  port: 80
  servlet:
    context-path: '/sample'

# swagger-ui config
springdoc:
  swagger-ui:
    operationSorter: alpha
    displayRequestDuration: true